name: Docker push 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Checkout the repository code

      - name: Set up Docker tag
        run: echo "TAG=$(date +%s)" >> $GITHUB_ENV  # Create a unique tag based on timestamp

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:${{ env.TAG }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push my-image-name:${{ env.TAG }}
